# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='enla_num',
            field=models.CharField(max_length=50, verbose_name='Número de linea '),
        ),
    ]
