# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20171127_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Ciudad '),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre cliente '),
        ),
        migrations.AlterField(
            model_name='codexit',
            name='num_code',
            field=models.IntegerField(unique=True, verbose_name='Código de salida '),
        ),
        migrations.AlterField(
            model_name='contract',
            name='num_contract',
            field=models.IntegerField(unique=True, verbose_name='Número contrato '),
        ),
        migrations.AlterField(
            model_name='dnis',
            name='num_des',
            field=models.IntegerField(blank=True, verbose_name='Número de desborde '),
        ),
        migrations.AlterField(
            model_name='dnis',
            name='num_dnis',
            field=models.BigIntegerField(unique=True, verbose_name='DNIS '),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='enla_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de linea '),
        ),
        migrations.AlterField(
            model_name='linext',
            name='num_linext',
            field=models.BigIntegerField(unique=True, verbose_name='Linea externa '),
        ),
        migrations.AlterField(
            model_name='plataform',
            name='name_plataform',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Plataforma '),
        ),
        migrations.AlterField(
            model_name='preexit',
            name='num_pref',
            field=models.IntegerField(unique=True, verbose_name='Prefijo de salida '),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name_seat',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Sede '),
        ),
        migrations.AlterField(
            model_name='trunk',
            name='num_trunk',
            field=models.IntegerField(unique=True, verbose_name='Número troncal '),
        ),
        migrations.AlterField(
            model_name='typetrunk',
            name='type_trunk',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo Troncal '),
        ),
    ]
