# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171127_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnis',
            name='num_des',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de desborde '),
        ),
    ]
