# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20171127_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnis',
            options={'ordering': ['num_dnis'], 'verbose_name': 'DNIS', 'verbose_name_plural': 'DNIS'},
        ),
        migrations.AddField(
            model_name='trunkenlace',
            name='obser',
            field=models.TextField(blank=True, max_length=100, verbose_name='Observación'),
        ),
    ]
