# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171219_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preexit',
            options={'ordering': ['num_pref'], 'verbose_name': 'Prefijo de salida', 'verbose_name_plural': 'Prefijos de salida'},
        ),
        migrations.RemoveField(
            model_name='enlace',
            name='enla_proex',
        ),
        migrations.AlterField(
            model_name='contract',
            name='num_contract',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número contrato '),
        ),
        migrations.AlterField(
            model_name='dnis',
            name='num_des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de desborde '),
        ),
        migrations.AlterField(
            model_name='dnis',
            name='num_dnis',
            field=models.CharField(max_length=255, unique=True, verbose_name='DNIS '),
        ),
        migrations.AlterField(
            model_name='linext',
            name='num_linext',
            field=models.CharField(max_length=255, unique=True, verbose_name='Linea externa '),
        ),
        migrations.AlterField(
            model_name='trunk',
            name='num_trunk',
            field=models.CharField(max_length=250, unique=True, verbose_name='Número troncal '),
        ),
    ]
